### ISSUE TITLE
Submitted CP checkpoint does not correspond to the model architecture in the current version

### ISSUE THREAD

**Issue by ShantIssa** [owj0421/OutfitTransformer#7]
Run: ``` python cp_test.py --task $TASK --polyvore_split nondisjoint --test_batch 96 --data_dir $DATA_DIR --checkpoint $CHECKPOINT```

Output
```INFO:albumentations.check_version:A new version of Albumentations is available: 1.4.11 (you have 1.4.8). Upgrade using: pip install --upgrade albumentations
/Users/user_name/.pyenv/versions/3.9.16/lib/python3.9/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: dlopen(/Users/user_name/.pyenv/versions/3.9.16/lib/python3.9/site-packages/torchvision/image.so, 0x0006): Symbol not found: __ZN2at4_ops19empty_memory_format4callEN3c108ArrayRefINS2_6SymIntEEENS2_8optionalINS2_10ScalarTypeEEENS6_INS2_6LayoutEEENS6_INS2_6DeviceEEENS6_IbEENS6_INS2_12MemoryFormatEEE
  Referenced from: <3F789787-FE38-3CE7-8599-064BDD0416EE> /Users/user_name/.pyenv/versions/3.9.16/lib/python3.9/site-packages/torchvision/image.so
  Expected in:     <98993E81-78F8-3504-938B-4D1F9450D4C6> /Users/user_name/.pyenv/versions/3.9.16/lib/python3.9/site-packages/torch/lib/libtorch_cpu.dylib
  warn(f"Failed to load image Python extension: {e}")
Use OutfitTransformer Embedding for recommendation.
/Users/user_name/.pyenv/versions/3.9.16/lib/python3.9/site-packages/huggingface_hub/file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
Traceback (most recent call last):
  File "/Users/user_name/Desktop/OutfitTransformer/cp_test.py", line 75, in <module>
    model, input_processor = load_model(args)
  File "/Users/user_name/Desktop/OutfitTransformer/src/models/load.py", line 56, in load_model
    recommendation_model.load_state_dict(state_dict)
  File "/Users/user_name/.pyenv/versions/3.9.16/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1604, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for RecommendationModel:
        Missing key(s) in state_dict: "embedding_model.text_encoder.embeddings.position_ids". 
```

**Comment by karen-petrosian** [comment]
Having the same problem as well. Seems like the provided checkpoints do not match with the model's architecture
